name: dmi_2022
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.0.1
  - pip:
      - numpy==1.24.3
      - pandas==2.0.1
      - pytz==2023.3
      - scipy==1.10.1
      - tzdata==2023.3
      - ipykernel==6.19.2
      - ipython==8.12.0
      - asttokens==2.0.5
      - backcall==0.2.0
      - comm==0.1.2
      - debugpy==1.5.1
      - decorator==5.1.1
      - executing==0.8.3
      - jedi==0.18.1
      - jupyter_client==8.1.0
      - jupyter_core==5.3.0
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.6
      - packaging==23.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==2.5.2
      - prompt-toolkit==3.0.36
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure_eval==0.2.2
      - python-dateutil==2.8.2
      - pyzmq==25.0.2
      - setuptools==66.0.0
      - six==1.16.0
      - stack_data==0.2.0
      - tornado==6.2
      - traitlets==5.7.1
      - wcwidth==0.2.5
      - wheel==0.38.4
      
  
  
